### ISSUE TITLE
Rename this repo to GhidraREFramework

### ISSUE THREAD

**Issue by illusionyy** [Fexty12573/GhidraREFramework#1]
Found this from praydog on this discord, didn't know this is even for REFramework

**Comment by Fexty12573** [comment]
Have you tested this with other RE Engine games? I don't see why it wouldn't work but I want to know be certain.

**Comment by illusionyy** [comment]
Tried with RE8 and DD2 and it does all work. though I have to manually enter class filters, `via`/`app`/`System`, etc for them to be labeled

**Comment by Fexty12573** [comment]
Right. I'll change that then
